from extras import relPath

template_file = ''
map_svg_file = ''

# Read

with open(relPath('../mapping/template.html'), 'r') as file:
    template_file = file.read()

with open(relPath('../outputs/betterMap.svg'), 'r') as file:
    map_svg_file = file.read()

# Modify

index_file = template_file.replace('{{ MAP SVG }}', map_svg_file)
index_file = index_file.replace('{{ WARNING }}', '<!-- ------------------ DO NOT EDIT THIS FILE! ------------------ -->')

# Write

with open(relPath('../index.html'), 'w') as f:
    f.write(index_file)